const data = [
  {
    ssn: "245798",
    name: "abdu",
    last: "Jhon",
    salary: "$45,000",
    occupation: "FrontEnd Developer",
    type: "Contractual",
  },
  {
    ssn: "955798",
    name: "Jane",
    last: "Just",
    salary: "$15,000",
    occupation: "Accountant",
    type: "Permanent",
  },
  {
    ssn: "2005798",
    name: "Hary",
    last: "Wilson",
    salary: "$65,000",
    occupation: "DevOps Engineer",
    type: "FreeLance",
  },
  {
    ssn: "245798",
    name: "abdu",
    last: "Jhon",
    salary: "$45,000",
    occupation: "FrontEnd Developer",
    type: "Contractual",
  },
  {
    ssn: "955798",
    name: "Jane",
    last: "Just",
    salary: "$15,000",
    occupation: "Accountant",
    type: "Permanent",
  },
  {
    ssn: "2005798",
    name: "Hary",
    last: "Wilson",
    salary: "$65,000",
    occupation: "DevOps Engineer",
    type: "FreeLance",
  },
  {
    ssn: "245798",
    name: "Yup  Jho",
    last: "Jhon",
    salary: "$45,000",
    occupation: "FrontEnd Developer",
    type: "Contractual",
  },
  {
    ssn: "955798",
    name: "Jane",
    last: "Just",
    salary: "$15,000",
    occupation: "Accountant",
    type: "Permanent",
  },
  {
    ssn: "2005798",
    name: "Hary",
    last: "Wilson",
    salary: "$65,000",
    occupation: "DevOps Engineer",
    type: "FreeLance",
  },
  {
    ssn: "245798",
    name: "abdu",
    last: "Jhon",
    salary: "$45,000",
    occupation: "FrontEnd Developer",
    type: "Contractual",
  },
  {
    ssn: "955798",
    name: "Jane",
    last: "Just",
    salary: "$15,000",
    occupation: "Accountant",
    type: "Permanent",
  },
  {
    ssn: "2005798",
    name: "Hary",
    last: "Wilson",
    salary: "$65,000",
    occupation: "DevOps Engineer",
    type: "FreeLance",
  },
  {
    ssn: "245798",
    name: "abdu",
    last: "Jhon",
    salary: "$45,000",
    occupation: "FrontEnd Developer",
    type: "Contractual",
  },
  {
    ssn: "955798",
    name: "Jane",
    last: "Just",
    salary: "$15,000",
    occupation: "Accountant",
    type: "Permanent",
  },
  {
    ssn: "2005798",
    name: "Hary",
    last: "Wilson",
    salary: "$65,000",
    occupation: "DevOps Engineer",
    type: "FreeLance",
  },
  {
    ssn: "245798",
    name: "Yup  Jho",
    last: "Jhon",
    salary: "$45,000",
    occupation: "FrontEnd Developer",
    type: "Contractual",
  },
  {
    ssn: "955798",
    name: "Jane",
    last: "Just",
    salary: "$15,000",
    occupation: "Accountant",
    type: "Permanent",
  },
  {
    ssn: "2005798",
    name: "Hary",
    last: "Wilson",
    salary: "$65,000",
    occupation: "DevOps Engineer",
    type: "FreeLance",
  },
];
export default data;
